### ISSUE TITLE
Android performance

### ISSUE THREAD

**Issue by domagojmedo** [gabrielfreire/IMSCovid19Tracker#1]
Hi, adding widgets to main dashboard reduces performance significantly. When I remove all the widgets it goes back to working perfectly and adding them back degrades performance back to what feels like 5 FPS.

Even adding just 1 or 2 widgets slows the app down a lot

Using OnePlus 3T

**Comment by gabrielfreire** [comment]
Hi @domagojmedo , thank you for reporting this.

Can you tell me what android version you're using ?
 
Unfortunately i don't have this device here, i've tried reproducing your issue using multiple Emulators from `128mb` of memory forward but with no success.
The only android physical device i have available is a very fast one, Samsung Galaxy S10 which runs everything very smoothly.

But i will investigate further, thank you.

**Comment by domagojmedo** [comment]
https://youtu.be/0iVcie9uU8s

In both cases I'm making same scroll gesture, but you can see it's much smoother at the end of the video.

Also I'm using Android 8

**Comment by gabrielfreire** [comment]
Thanks for the video, very helpful.

Although i can't reproduce this issue, maybe i should try to make the app more performant for less performant devices by using less `StackLayout` in the widgets, i wouldn't be able to test properly though, but i will investigate this anyway.

Thank you again.

**Comment by gabrielfreire** [comment]
This is a very good article about `StackLayout` vs `Grid` performance: 
https://ericsink.com/entries/xf_measure.html

I will make the changes for a next version, unfortunately i don't have an automatic App update mechanism in place, but will post here once i have a better performant version available.

*p.s. i use a lot of StackLayouts hehe*

**Comment by gabrielfreire** [comment]
Hey @domagojmedo , i've just created a new release 2.2.1 that includes all fixes and performance improvements for the UI. You can use the same link as the Twitter post to install, let me know if you still get performance problems.

I believe that the main problem is `CollectionView` is a very memory heavy component and old devices seem to struggle.

Thanks for all the help.

**Comment by domagojmedo** [comment]
Unfortunately it's still not working smoothly, I forked the project and will try to see what's happening since I have the device that's causing issues. It's an older phone but should still be more than enough to handle collection view with 6 items I would hope

**Comment by gabrielfreire** [comment]
Hey @domagojmedo , 

> Unfortunately it's still not working smoothly


Oh that's unfortunate. 

> I forked the project and will try to see what's happening since I have the device that's causing issues.

Great stuff, that would be really helpful, thanks very much.

**Comment by domagojmedo** [comment]
It's the image confirmed.png in CovidInformationCard.xaml. That image is 1500x1500, that's definetly too large for an icon :)
After resizing it, everything works smoothly. You should probably double check other images for size

**Comment by gabrielfreire** [comment]
>  You should probably double check other images for size

Haha, will do, thanks for that
