### ISSUE TITLE
Help shows on every launch

### ISSUE THREAD

**Issue by domagojmedo** [gabrielfreire/IMSCovid19Tracker#2]
![Screenshot_20200503-155737__01](https://user-images.githubusercontent.com/12157224/80916095-ee200080-8d56-11ea-96bf-e8fd3e68e8a2.jpg)

This shows on every launch. Should probably only show on first launch

**Comment by domagojmedo** [comment]
You can achieve same thing with https://docs.microsoft.com/en-us/xamarin/essentials/version-tracking?context=xamarin/xamarin-forms

**Comment by gabrielfreire** [comment]
I used Essentials for the Storage to detect if the app was launched for the first time, which is the same feature i use to store user's widget configuration

**Comment by domagojmedo** [comment]
Yes, I was just pointing out that essentials already have API for detecting if this is first launch ever/for this version

**Comment by gabrielfreire** [comment]
Geez, very good, sorry i didn't see it. Thanks
