### ISSUE TITLE
View reference in ViewModel

### ISSUE THREAD

**Issue by domagojmedo** [gabrielfreire/IMSCovid19Tracker#4]
I think ViewModel should have 0 references to the view/page it represents. Page has Binding contract and can call things from ViewModel, but ViewModel shouldn't be setting view height and stuff like that. 
That's one of the main points of ViewModel.

I noticed you are setting HeightRequest in VM in latest performance commit and just wanted to point that out.

**Comment by gabrielfreire** [comment]
Thanks for the advice, i'm new to Xamarin and will fix this to use best practices
